### ISSUE TITLE
JOSS Paper: State of Field

### ISSUE THREAD

**Issue by shyamd** [alexmalins/radioactivedecay#31]
Hi Alex,

Can you add a few sentences on what challenges a user might face using `pyNE` or `Radiological toolbox` that `radioactivedecay` aims to solve. It's sort of hinted at in the capabilities and validation, but it would be useful to be very clear about this, maybe at the end of the `Statement of Need` section.

**Comment by alexmalins** [comment]
Hi Shyam,

Thanks for this comment and for starting your review. I added a new para into the `Statement of Need` section accordingly (https://github.com/alexmalins/radioactivedecay/commit/1ba6ca40985e88271cd8c8af1046b8cf3a0e2fb0). Happy hear your thoughts and any further comments if you have them.

**Comment by shyamd** [comment]
Thanks! That is perfect.

**Comment by alexmalins** [comment]
Thanks @shyamd
