### ISSUE TITLE
JOSS Documentation

### ISSUE THREAD

**Issue by munkm** [alexmalins/radioactivedecay#38]
The documentation for this package is nicely written and guides potential users through the software and API well. Based on the reviewer checklist in https://github.com/openjournals/joss-reviews/issues/3318, I think a few minor enhancements can be made. 

- [x] **statement of need** You mention what the package does, but you don't explicitly state who the target audience for the software is in the documentation
- [x] **community guidelines** Do you have a preferred way for users to seek out support or ask questions? There are instructions for feature requests and bugfixes, but what about questions outside of these? 
- [x] **testing** The package does have a tests directory, but I don't see on https://alexmalins.com/radioactivedecay/ that there are steps described on how to run the tests to check one's installation. Did I miss it?

**Comment by alexmalins** [comment]
Hi @munkm,

Thanks for your review and these suggestions. I incorporated them all. The changes are visible within the [doc/source](https://github.com/alexmalins/radioactivedecay/tree/devel/docs/source) folder of the devel branch (apologies the commit history is not so clear as some of the changes were incorporated as part of a large refactor). Once we release the next version, the changes will go live on https://alexmalins.com/radioactivedecay/.

**Comment by munkm** [comment]
Awesome! I think this issue can be closed, then!

**Comment by alexmalins** [comment]
Great, thanks!
